### ISSUE TITLE
BeliefBox is not a Bayesian RL library

### ISSUE THREAD

**Issue by PhilippeMorere** [aikorea/awesome-rl#27]
BeliefBox is not a Bayesian RL library.
From Christos Dimitrakakis's website,  it is a statistical inference and decision making toolbox.
I quickly skimmed through it and could not find any Bayesian RL method implemented (QLearning, BEETLE, GPTD, ...).

**Comment by hshyunsookim** [comment]
I see there are has some Bayesian RL (or related) algorithms (BVMM, Bayesian MC, Bayesian Multi-Task Inverse RL, etc.). Closing the issue.
