### ISSUE TITLE
Wrong year in "Autonomous helicopter control..." paper

### ISSUE THREAD

**Issue by kvrigor** [aikorea/awesome-rl#39]
The publication year must be 2001 instead of 2011 ([refer to line 166](https://github.com/aikorea/awesome-rl/blame/master/README.md#L166))

> - Autonomous helicopter control using Reinforcement Learning Policy Search Methods (Bagnell, ICRA **2001**)

[Referenced paper](http://repository.cmu.edu/cgi/viewcontent.cgi?article=1082&context=robotics) | [Google Scholar search](https://scholar.google.com/scholar?hl=en&as_sdt=0%2C5&q=Autonomous+helicopter+control+using+reinforcement+learning+policy+search+methods&btnG=)

**Comment by hshyunsookim** [comment]
Thanks!
