### ISSUE TITLE
Reinforcement Learning: An Introduction has a new draft

### ISSUE THREAD

**Issue by enabrintain** [aikorea/awesome-rl#54]
Richard Sutton and Andrew Barto, Reinforcement Learning: An Introduction (2nd Edition, in progress, 2018) can now point to
http://incompleteideas.net/book/bookdraft2018mar11.pdf

instead of 

http://incompleteideas.net/book/bookdraft2018jan1.pdf

cheers!

**Comment by mithi** [comment]
[Here's the final 2nd edition if I'm not mistaken.](http://incompleteideas.net/book/RLbook2018.pdf) :heart:

**Comment by mithi** [comment]
Thanks! for merging! ❤️
